<a href="https://colab.research.google.com/github/habib-wahid/ML-Assignment/blob/main/cost_function_minimize_using_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Data/4K_House_Rent_Dataset.csv")
data.head()

Posted On  BHK   Rent  Size            Floor    Area Type  \
0  2022-05-18    2  10000  1100  Ground out of 2   Super Area   
1  2022-05-13    2  20000   800       1 out of 3   Super Area   
2  2022-05-16    2  17000  1000       1 out of 3   Super Area   
3  2022-07-04    2  10000   800       1 out of 2   Super Area   
4  2022-05-09    2   7500   850       1 out of 2  Carpet Area   

              Area Locality     City Furnishing Status  Tenant Preferred  \
0                    Bandel  Kolkata       Unfurnished  Bachelors/Family   
1  Phool Bagan, Kankurgachi  Kolkata    Semi-Furnished  Bachelors/Family   
2   Salt Lake City Sector 2  Kolkata    Semi-Furnished  Bachelors/Family   
3               Dumdum Park  Kolkata       Unfurnished  Bachelors/Family   
4             South Dum Dum  Kolkata       Unfurnished         Bachelors   

   Bathroom Point of Contact  
0         2    Contact Owner  
1         1    Contact Owner  
2         1    Contact Owner  
3         1    Contact Owner  
4         1    Contact Owner

In [ ]:
Y = data['Rent'].values
print(Y)
X1 = data['Size'].values
X2 = data['BHK'].values
X3 = data['City'].values
X4 = data['Bathroom'].values
X5 = data['Furnishing Status'].values

[10000 20000 17000 ... 35000 45000 15000]


In [ ]:
def replace_feature_by_value(input_list,replacing_item,replaced_value):
  return [replaced_value if item == replacing_item else item for item in input_list]

X3 = replace_feature_by_value(X3,'Bangalore',1)
X3 = replace_feature_by_value(X3,'Chennai',2)
X3 = replace_feature_by_value(X3,'Delhi',3)
X3 = replace_feature_by_value(X3,'Hyderabad',4)
X3 = replace_feature_by_value(X3,'Kolkata',5)
X3 = replace_feature_by_value(X3,'Mumbai',6)

X5 = replace_feature_by_value(X5,'Furnished',1)
X5 = replace_feature_by_value(X5,'Semi-Furnished',2)
X5 = replace_feature_by_value(X5,'Unfurnished',3)

print(type(X1[0]),type(X2[0]),type(X3[0]),type(X4[0]),type(X5[0]))

<class 'numpy.int64'> <class 'numpy.int64'> <class 'int'> <class 'numpy.int64'> <class 'int'>


In [ ]:
Y = np.asmatrix(Y)
print(Y)
Y = np.transpose(Y)
print(Y)

[[10000 20000 17000 ... 35000 45000 15000]]
[[10000]
 [20000]
 [17000]
 ...
 [35000]
 [45000]
 [15000]]


In [ ]:
print(len(X1),len(X2),len(X3),len(X4),len(X5))

4746 4746 4746 4746 4746


In [ ]:
X = []
m = len(X1)
for i in range(m):
  temp_lst = []
  temp_lst.append(1)
  temp_lst.append(X1[i])
  temp_lst.append(X2[i])
  temp_lst.append(X3[i])
  temp_lst.append(X4[i])
  temp_lst.append(X5[i])
  X.append(temp_lst)

X = np.asmatrix(X)
print(X)


[[   1 1100    2    5    2    3]
 [   1  800    2    5    1    2]
 [   1 1000    2    5    1    2]
 ...
 [   1 1750    3    4    3    2]
 [   1 1500    3    4    2    2]
 [   1 1000    2    4    2    3]]


**Normal Equation Calculation**

In [ ]:
x_trans_x = np.matmul(X.T,X)
print(x_trans_x)

[[      4746    4591711       9890      16407       9330      10627]
 [   4591711 6350936573   11362068   15605622   10998301    9925588]
 [      9890   11362068      23896      34521      22219      21766]
 [     16407   15605622      34521      71875      33066      36753]
 [      9330   10998301      22219      33066      22054      20370]
 [     10627    9925588      21766      36753      20370      26019]]


In [ ]:
x_trans_y = np.matmul(X.T,Y)
print(x_trans_y)

[[   166078920]
 [257882791665]
 [   460123311]
 [   713580761]
 [   471128360]
 [   334770701]]


In [ ]:
from numpy.linalg import inv
inv_x_trans_x = inv(x_trans_x)
print(inv_x_trans_x)

[[ 5.10166440e-03  2.28122623e-08 -5.48853222e-04 -2.01190854e-04
  -2.49174344e-04 -1.15398073e-03]
 [ 2.28122623e-08  1.33637616e-09 -3.40021261e-07  5.57081397e-08
  -4.60931725e-07  4.74997363e-08]
 [-5.48853222e-04 -3.40021261e-07  9.16512440e-04  1.17595825e-06
  -5.07550907e-04 -1.71276239e-05]
 [-2.01190854e-04  5.57081397e-08  1.17595825e-06  6.94048932e-05
  -4.59450135e-05 -2.12978422e-06]
 [-2.49174344e-04 -4.60931725e-07 -5.07550907e-04 -4.59450135e-05
   9.11332708e-04  5.36191635e-05]
 [-1.15398073e-03  4.74997363e-08 -1.71276239e-05 -2.12978422e-06
   5.36191635e-05  4.66995037e-04]]


In [ ]:
theta = np.matmul(inv_x_trans_x,x_trans_y)
print(theta)

[[-4.66563190e+04]
 [ 3.04611119e+01]
 [-1.14615583e+03]
 [ 8.66070487e+03]
 [ 2.07343616e+04]
 [-7.20533636e+03]]


In [ ]:
theta = np.squeeze(np.asarray(theta))
theta_0 = theta[0]
theta_1 = theta[1]
theta_2 = theta[2]
theta_3 = theta[3]
theta_4 = theta[4]
theta_5 = theta[5]

**Cost Function**

In [ ]:
sum = 0
for i in range(m):
  temp_sum = theta_0 + theta_1*X1[i] + theta_2*X2[i] + theta_3*X3[i] + theta_4*X4[i] + theta_5*X5[i]
  temp_sum = temp_sum ** 2
  sum += temp_sum

cost = sum/(2*m)
print(cost)

1381786252.4135602
